### GET / route

GET http://localhost:3000
Content-Type: application/json

### GET users

GET http://localhost:3000/users
Content-Type: application/json

### GET users/2

GET http://localhost:3000/users/2
Content-Type: application/json

### POST users
POST http://localhost:3000/users
Content-Type: application/json

{
    "name":"Emma",
    "email":"frgrg@rgt.com",
    "jelszo":"male123"
}

### DELETE user By ID

DELETE http://localhost:3000/users/4
Content-Type: :application/json

### PATCH user by id
PATCH http://localhost:3000/users/4
Content-Type: :application/json

{
    "name":"Bélaa",
    "age":25,
    "gender":"male"
}

### POST login

PATCH http://localhost:3000/users/login
Content-Type: application/json

{
    "email":"vj@vendo.baja",
    "password":"Vendo123"
    
}
